### ISSUE TITLE
How to identify a node individually created with the stage0 renderer

### ISSUE THREAD

**Issue by Leslieetubo** [retejs/stage0-render-plugin#8]
I am trying to call my node id's to use on my HTML template. Please, I need help, I am using the stage0 renderer and I can't find documentation on how to do this.

**Comment by trsh** [comment]
Yeah, need more details. I don't understand what u are doing and what is not working :)

**Comment by khalifagates** [comment]
I need to identify each created node's id to render it in the HTML template e.g <div id=${{node.id}}>. I need this in order to use jquery to open load unique content on each created node. I found a walkaround with the Vue renderer plugin, but I wanted to try to get the same effect with stage0 plugin.

**Comment by trsh** [comment]
```
var n1 = await components[0].createNode({ num: 3 });
console.log(n1);
```
id: 1

Like this?

**Comment by Ni55aN** [comment]
@khalifagates

> to use jquery to open load unique content on each created node

What a unique content? How did you implement it with Vue render plugin?

**Comment by trsh** [comment]
Closing dude inactivity.
